# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Digitizing the Dualism Debate"
email: fabian.moss@epfl.ch
description: >- # this means to ignore newlines until "baseurl:"
  This project applies methods from the Digital Humanities to the study of 
  a central debate in German 19th-century music theory, the "dualism debate".
  It strives to reconstruct and critically evaluate the discursive relations within
  this debate by using the combined power of qualitative-historical and quantitative-numerical methods.
baseurl: "/ddd" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: fabianmoss
github_username:  fabianmoss

# Build settings
markdown: kramdown

theme: minima

plugins:
  - jekyll-feed
  - github-pages
  - jekyll-scholar

scholar: 
  style: apa
  locale: en
  source: _bibliography

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
