# If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Digitizing the Dualism Debate"
email: fabian.moss@epfl.ch
description: >- # this means to ignore newlines until "baseurl:"
  This project applies methods from the Digital Humanities to the study of 
  a central debate in German 19th-century music theory, the "dualism debate".
  It strives to reconstruct and critically evaluate the discursive relations within
  this debate by using the combined power of qualitative-historical and quantitative-numerical methods.
baseurl: "/ddd" # the subpath of your site, e.g. /blog
url: "dcmlab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: fabianmoss
github_username:  fabianmoss

# Build settings
markdown: kramdown

theme: just-the-docs

plugins:
  - jekyll-feed
  - github-pages
  - jekyll-scholar

scholar: 
  style: apa
  locale: en
  source: _bibliography

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Set path to logo to be displayed instead of title in sidebar
# logo: "/assets/images/mus-fav.png"

# Enable site search
search_enabled: true

# Search function parameters
search:
  heading_leve: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

  # Change color scheme (available: dark or light)
  # color_scheme: dark
  # Custom color scheme: to add a scheme named foo, add a file _sass/color_schemes/foo.scss
  # Available variables are listed in the _variables.scss file
  # Then change color_scheme here

  # Aux links for the upper right navigation
aux_links:
  "DDD on GitHub":
    - "//github.com/DCMLab/ddd"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"